---
# tasks file for mysql

  - name: install repo for MySQL
    yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
      
  - name: install MySQL, MySQL-Python
    yum:
      name:
        - MySQL-python
        - mysql-community-server
      state: latest
     
  - name: Start MySQL
    ansible.builtin.systemd:
      name: mysqld
      state: started
      enabled: yes
     
  - name: check if .my.cnf exists
    stat:
      path: /root/.my.cnf
    register: my_cnf

  - name: Initial MySQL setup
    block:
  
      - name: grab temporary password from var/log/mysqld.log
        shell: cat /var/log/mysqld.log | grep "temporary password" | grep -oE '[^ ]+$'
        register: tmp_pass

      - name: MySQL, set new password for root user (only if .my.cnf file doesn't exist)
        shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ new_pass }}'');" --connect-expired-password -u root -p"{{ tmp_pass.stdout }}"'
      
      - name: copy my.cnf 
        template:
          src: my.cnf.j2
          dest: /root/.my.cnf
          owner: root
          mode: 0600
        notify:
          - Restart MySQL    
    
    when: my_cnf.stat.exists==False

  - name: create a database
    community.mysql.mysql_db:
      name: new_db1
      state: present

  - name: create a user
    community.mysql.mysql_user:
      name: alice
      password: blabla12
      priv: '*.*:ALL'
      state: present
